In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm

In [2]:
df=pd.read_csv("imdb_movies.csv")

In [3]:
df.head()

names       date_x  score  \
0                    Creed III  03/02/2023    73.0   
1     Avatar: The Way of Water  12/15/2022    78.0   
2  The Super Mario Bros. Movie  04/05/2023    76.0   
3                      Mummies  01/05/2023    70.0   
4                    Supercell  03/17/2023    61.0   

                                           genre  \
0                                  Drama, Action   
1             Science Fiction, Adventure, Action   
2  Animation, Adventure, Family, Fantasy, Comedy   
3  Animation, Comedy, Family, Adventure, Fantasy   
4                                         Action   

                                            overview  \
0  After dominating the boxing world, Adonis Cree...   
1  Set more than a decade after the events of the...   
2  While working underground to fix a water main,...   
3  Through a series of unfortunate events, three ...   
4  Good-hearted teenager William always lived in ...   

                                                crew  \
0  Michael B. Jordan, Adonis Creed, Tessa Thompso...   
1  Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...   
2  Chris Pratt, Mario (voice), Anya Taylor-Joy, P...   
3  Óscar Barberán, Thut (voice), Ana Esther Albor...   
4  Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...   

                    orig_title     status            orig_lang     budget_x  \
0                    Creed III   Released              English   75000000.0   
1     Avatar: The Way of Water   Released              English  460000000.0   
2  The Super Mario Bros. Movie   Released              English  100000000.0   
3                       Momias   Released   Spanish, Castilian   12300000.0   
4                    Supercell   Released              English   77000000.0   

        revenue country  
0  2.716167e+08      AU  
1  2.316795e+09      AU  
2  7.244590e+08      AU  
3  3.420000e+07      AU  
4  3.409420e+08      US

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10178 entries, 0 to 10177
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   names       10178 non-null  object 
 1   date_x      10178 non-null  object 
 2   score       10178 non-null  float64
 3   genre       10093 non-null  object 
 4   overview    10178 non-null  object 
 5   crew        10122 non-null  object 
 6   orig_title  10178 non-null  object 
 7   status      10178 non-null  object 
 8   orig_lang   10178 non-null  object 
 9   budget_x    10178 non-null  float64
 10  revenue     10178 non-null  float64
 11  country     10178 non-null  object 
dtypes: float64(3), object(9)
memory usage: 954.3+ KB


In [5]:
df.isna().sum()

names          0
date_x         0
score          0
genre         85
overview       0
crew          56
orig_title     0
status         0
orig_lang      0
budget_x       0
revenue        0
country        0
dtype: int64

In [6]:
df["genre"].fillna(df["genre"].mode()[0], inplace=True)
df["crew"].fillna('NA', inplace=True)

In [7]:
df.isna().sum()

names         0
date_x        0
score         0
genre         0
overview      0
crew          0
orig_title    0
status        0
orig_lang     0
budget_x      0
revenue       0
country       0
dtype: int64

In [8]:
df.shape

(10178, 12)

In [9]:
print(df["budget_x"].value_counts())

20000000.0     228
10000000.0     205
30000000.0     182
25000000.0     180
40000000.0     169
              ... 
41721862.6       1
115460000.0      1
27969400.0       1
137040000.0      1
9145817.8        1
Name: budget_x, Length: 2316, dtype: int64


In [10]:
# sns.countplot(x='budget_x',data=df)

In [11]:
df.columns

Index(['names', 'date_x', 'score', 'genre', 'overview', 'crew', 'orig_title',
       'status', 'orig_lang', 'budget_x', 'revenue', 'country'],
      dtype='object')

In [12]:
df.head(1)

names       date_x  score          genre  \
0  Creed III  03/02/2023    73.0  Drama, Action   

                                            overview  \
0  After dominating the boxing world, Adonis Cree...   

                                                crew orig_title     status  \
0  Michael B. Jordan, Adonis Creed, Tessa Thompso...  Creed III   Released   

  orig_lang    budget_x      revenue country  
0   English  75000000.0  271616668.0      AU

In [13]:
x = df.iloc[:, np.r_[2:3, 8:10]].values
y = df.iloc[:, 10].values
print(x[0])
print(y[0])

[73.0 ' English' 75000000.0]
271616668.0


In [14]:
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.preprocessing import LabelEncoder
Labelencoder_x=LabelEncoder()

In [15]:
for i in  range(0,3):
    x_train[:,i]=Labelencoder_x.fit_transform(x_train[:,i])
x_train   

array([[50, 45, 283],
       [45, 12, 875],
       [50, 12, 637],
       ...,
       [47, 12, 1590],
       [39, 12, 1173],
       [34, 12, 1657]], dtype=object)

In [16]:
Labelencoder_y=LabelEncoder()
y_train=Labelencoder_y.fit_transform(y_train)
y_train 

array([2763, 1039, 1438, ..., 5655, 4838, 4988], dtype=int64)

In [17]:
for i in  range(0,3):
    x_test[:,i]=Labelencoder_x.fit_transform(x_test[:,i])
x_test   

array([[36, 7, 773],
       [38, 7, 248],
       [54, 7, 207],
       ...,
       [44, 7, 385],
       [36, 7, 288],
       [33, 7, 425]], dtype=object)

In [18]:
Labelencoder_y=LabelEncoder()
y_test=Labelencoder_y.fit_transform(y_test)
y_test 

array([1093,  516,  653, ...,  629, 1079, 1420], dtype=int64)

In [19]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [20]:
y_pred = reg.predict(x_test)
y_pred

array([2547.03152005, 1156.52209077, 1497.2210399 , ..., 1704.32386889,
       1210.0717759 , 1502.65589184])

In [21]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

-0.4869656098093411